# Generated by Django 4.1.2 on 2022-10-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_employee_department_employee_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Company Number',
            },
        ),
    ]
