# Generated by Django 4.1.2 on 2022-10-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name_plural': 'Status'},
        ),
    ]
