# Generated by Django 4.1.2 on 2022-10-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_api', '0002_employee_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manual_employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
